import BalloonBackground from '../components/BalloonBackground';
import ConfettiCanvas from '../components/ConfettiCanvas';
import SunriseBackground from '../components/SunriseBackground';
import PlaneBackground from '../components/PlaneBackground';
import CloudBackground from '../components/CloudBackground';
import CityBackground from '../components/CityBackground';
import FireworksCanvas from '../components/FireworksCanvas';
import OceanCanvas from '../components/OceanCanvas';

export const greetingsConfig = [
  {
    id: 1,
    icon: '🎈',
    heading: 'Happy Birthday!',
    message: 'Wishing you a day as bright and colourful as these balloons. May every moment lift your spirits sky-high! 🎈',
    backgroundGradient: 'linear-gradient(180deg, #87ceeb 0%, #c8e6ff 60%, #e8f4ff 100%)',
    cardStyle: {
      padding: '40px 48px',
      background: 'rgba(255,255,255,0.45)',
      borderRadius: '24px',
      backdropFilter: 'blur(10px)',
      boxShadow: '0 8px 32px rgba(0,0,0,0.15)',
      headingColor: '#ff4757',
      messageColor: '#444',
    },
    BackgroundComponent: BalloonBackground,
    containerClassName: 'birthday-card',
  },
  {
    id: 2,
    icon: '🎉',
    heading: 'Happy Birthday!',
    message: 'May your special day be showered with confetti, laughter, and all the things that make you smile! 🎊',
    backgroundGradient: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)',
    cardStyle: {
      padding: '48px 56px',
      background: 'rgba(255,255,255,0.08)',
      borderRadius: '24px',
      border: '1px solid rgba(255,255,255,0.15)',
      backdropFilter: 'blur(12px)',
      boxShadow: '0 8px 40px rgba(0,0,0,0.4)',
      headingColor: '#ffd700',
      messageColor: '#ddeeff',
    },
    BackgroundComponent: ConfettiCanvas,
    containerClassName: 'confetti-card',
  },
  {
    id: 3,
    icon: '🌅',
    heading: 'Happy Birthday!',
    message: 'A new day rises, just for you — may it shine as brilliantly as you do! ☀️',
    backgroundGradient: null,
    cardStyle: {
      position: 'absolute',
      top: '8%',
      width: '100%',
      textAlign: 'center',
      padding: '20px',
      zIndex: 10,
      opacity: 0,
      headingColor: '#fff',
      messageColor: '#fff',
      textShadow: true,
    },
    BackgroundComponent: SunriseBackground,
    containerClassName: 'greeting',
  },
  {
    id: 4,
    icon: '✈️',
    heading: 'Happy Birthday!',
    message: 'Your birthday wishes are flying high! May this year take you to amazing new destinations full of joy and adventure. ✈️',
    backgroundGradient: 'linear-gradient(180deg, #56ccf2 0%, #2f80ed 50%, #b2e0f7 100%)',
    cardStyle: {
      padding: '40px 48px',
      background: 'rgba(255,255,255,0.45)',
      borderRadius: '24px',
      backdropFilter: 'blur(10px)',
      boxShadow: '0 8px 32px rgba(0,0,0,0.15)',
      headingColor: '#1565c0',
      messageColor: '#444',
    },
    BackgroundComponent: PlaneBackground,
    containerClassName: 'plane-card',
  },
  {
    id: 5,
    icon: '☁️',
    heading: 'Happy Birthday!',
    message: 'May your birthday be as light and carefree as floating on a cloud — drifting through a sky full of happiness and wonder! ☁️',
    backgroundGradient: 'linear-gradient(180deg, #c9e8f5 0%, #e8f6ff 50%, #f0f9ff 100%)',
    cardStyle: {
      padding: '40px 48px',
      background: 'rgba(255,255,255,0.55)',
      borderRadius: '32px',
      backdropFilter: 'blur(12px)',
      boxShadow: '0 8px 40px rgba(100,160,255,0.2)',
      border: '1px solid rgba(255,255,255,0.7)',
      headingColor: '#1a6fa8',
      messageColor: '#3a5f7a',
    },
    BackgroundComponent: CloudBackground,
    containerClassName: 'cloud-card',
  },
  {
    id: 6,
    icon: '🌃',
    heading: 'Happy Birthday!',
    message: 'The city lights up just for you tonight! May your birthday shine as brilliantly as a skyline full of a million glowing windows. 🌆',
    backgroundGradient: 'linear-gradient(180deg, #050510 0%, #0d0d2b 40%, #1a1040 100%)',
    cardStyle: {
      padding: '48px 56px',
      background: 'rgba(10,10,30,0.6)',
      borderRadius: '24px',
      border: '1px solid rgba(255,215,0,0.25)',
      backdropFilter: 'blur(14px)',
      boxShadow: '0 8px 40px rgba(0,0,0,0.6)',
      headingColor: '#ffd700',
      messageColor: '#ddeeff',
    },
    BackgroundComponent: CityBackground,
    containerClassName: 'city-card',
  },
  {
    id: 7,
    icon: '❤️',
    heading: 'ענבר, מזל טוב ליום הולדת שמח!',
    message: 'לעוד שנים ארוכות של חברות!',
    backgroundGradient: '#05050f',
    cardStyle: {
      padding: '28px 36px',
      maxWidth: '420px',
      background: 'rgba(255,255,255,0.06)',
      borderRadius: '24px',
      border: '1px solid rgba(255,255,255,0.12)',
      backdropFilter: 'blur(12px)',
      boxShadow: '0 8px 40px rgba(0,0,0,0.5)',
      headingColor: 'transparent',
      messageColor: '#ddeeff',
      headingFontSize: 'clamp(2.3rem, 7vw, 4rem)',
      messageFontSize: 'clamp(1.1rem, 3vw, 1.5rem)',
    },
    BackgroundComponent: FireworksCanvas,
    containerClassName: 'fireworks-card',
  },
  {
    id: 8,
    icon: '🐠',
    heading: 'Happy Birthday!',
    message: 'Dive deep into joy — the ocean of happiness is vast and it is all yours today! May your birthday be as vibrant as a coral reef. 🌊',
    backgroundGradient: null,
    cardStyle: {
      padding: '48px 56px',
      background: 'rgba(0,30,80,0.55)',
      borderRadius: '24px',
      border: '1px solid rgba(100,220,255,0.2)',
      backdropFilter: 'blur(14px)',
      boxShadow: '0 8px 40px rgba(0,0,0,0.5)',
      headingColor: '#00dfff',
      messageColor: '#b2eeff',
    },
    BackgroundComponent: OceanCanvas,
    containerClassName: 'ocean-card',
  },
];
